### ISSUE TITLE
Does it work with Arduino 1.6.9?

### ISSUE THREAD

**Issue by maxholgasson** [Simsso/ShiftRegister74HC595#1]
Hi,

doenst work on a Arduino Nano neither on a ESP8266

Does it work with IDE 1.6.9 ?

**Comment by Simsso** [comment]
Unfortunately I can't see an issue here.

The library works with version 1.6.13
![image](https://cloud.githubusercontent.com/assets/6556307/20635595/6e8c49a2-b35f-11e6-926f-218073d08172.png)
