### ISSUE TITLE
Use `setAll` with multiple shift registers

### ISSUE THREAD

**Issue by Muhammed-Hayr-Ali** [Simsso/ShiftRegister74HC595#13]
Thanks for this wonderful work
```cpp
// sets all pins at once (pin 0 low, pin 1 high, ...)
uint8_t pinValues[] = { B10101010 };
sr.setAll(pinValues); 
```
How can I use this property with a second shift registers just without affecting the first shift registers

**Comment by Simsso** [comment]
There is currently no explicit method that sets all eight outputs of a shift register (SR) at once, in multi shift register mode. There are, however, two ways of solving the problem: 

1. Use the `setNoUpdate(int pin, uint8_t value)` method to set all eight pins of the specific shift register and update it afterwards with `updateRegisters()`.
2. Retrieve the current state with `uint8_t * getAll()`, alter it as desired, and pass it to `setAll(uint8_t * digitalValues)`.

_Please close the issue if that resolves the problem._

**Comment by Muhammed-Hayr-Ali** [comment]
thank you for good working
