### ISSUE TITLE
getAll() for multiple shift registers

### ISSUE THREAD

**Issue by lnorton89** [Simsso/ShiftRegister74HC595#16]
Maybe I'm not reading the documentation correctly but how would one get the status of all shift register outputs to print to the Serial console?

**Comment by Simsso** [comment]
Hi @lnorton89:
One way of achieving this is the following:

1. Retrieve the values with `uint8_t * vals = sr.getAll()`.
2. Loop over the number of shift registers, counter variable `i`
3. For each shift register call `Serial.println(vals[i], BIN)`

Please close the issue if this answers your question.

**Comment by lnorton89** [comment]
I have two shift registers the first one being for outputs the second one for inputs. 

This seems to output the correct state of my output registers (1-8) but the first input register (9) is not being read. I am pulling it down to ground with a button. Is this correct?
```    
void setup() {
  Serial.begin(9600);
  sr.setAllHigh(); // set all pins HIGH
  sr.set(4, LOW); // equivalent to sr.set(pin, 1);
}
void loop() {
   uint8_t * vals = sr.getAll();
   for (int i=0; i< 2; i++) {
      Serial.println(vals[i], BIN);
   }
}
10:26:03.561 -> 11101111
10:26:03.561 -> 11111111

**Comment by Simsso** [comment]
The code looks good, however, you cannot use shift register pins like input pins. That's simply not possible with the 74HC595.

**Comment by lnorton89** [comment]
I was under the assumption it was possible. It would be nice to use a library like yours to read inputs instead of the SPI library. 

https://www.youtube.com/watch?v=nXl4fb_LbcI

**Comment by Simsso** [comment]
Thank you for pointing this out. I'm a bit surprised, also because the [data sheet](https://shiftregister.simsso.de/data-sheet.pdf) clearly states that the pins are outputs. However, they also say "8-bit serial input", so you seem to be right. I'd add this to the future features list of this library.
