### ISSUE TITLE
Extension library .hpp include as .h in .cpp

### ISSUE THREAD

**Issue by Cesar-S** [Simsso/ShiftRegister74HC595#20]
Hi, in file .cpp,  .hpp include as .h in, cause error.

br

**Comment by Simsso** [comment]
I cannot reproduce the error, for me the library compiles just fine on MacOS with Arduino version 1.8.10. Which setup are you using, do you still face the error?

**Comment by Cesar-S** [comment]
sorry, it's not a library error, we are using it in XOD and the builder change

as I didn't know how to implement it with <size> I used the previous version of the library again

Thanks
