### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by itsboo07** [Simsso/ShiftRegister74HC595#26]
hi again ..does this lib support esp32 and esp8266?

**Comment by sfranzyshen** [comment]
I personally have not tested it ... but this driver (Arduino Library) use the digitalwrite() and shiftout() function to write data out to the shift registers ... and does not rely on any platform specific resources ... So "Yes" it should work fine on the espX platforms ... :smile:

**Comment by itsboo07** [comment]
@sfranzyshen thanks for your response mate.. will try it out and update you..

**Comment by Simsso** [comment]
Feel encouraged to share your experience in this thread, @itsboo07, I'm curious too. 🙂
