### ISSUE TITLE
[Newbies] How to set this module ?

### ISSUE THREAD

**Issue by BullzLabz** [Simsso/ShiftRegister74HC595#28]
Hello, 

Thanks for your hard work on this library.

I read all your documentation and read your tutorial and test your examples but being beginner I'm not sure I understand.

I have a module of 4 digits but with two 74HC595 chip at the back PCB, which setting should I adjust my sketch please? 2 or 4?

[My module :](https://fr.aliexpress.com/item/1005002672324823.html?spm=a2g0o.productlist.0.0.83db2e77Pj02WT&algo_pvid=af3f80fe-b5bf-45a4-8e29-48f589619667&algo_exp_id=af3f80fe-b5bf-45a4-8e29-48f589619667-24)

![4 Digits Module](https://ae01.alicdn.com/kf/Hf0329bfd5ca44e3fb4cf91fdc3f4f7b6e/Tube-num-rique-LED-rouge-de-0-36-pouces-4-Bits-4-Bits-Module-d-affichage.jpg_Q90.jpg)

![4 Digits Module Back](https://ae01.alicdn.com/kf/Hf937fab545224c2d861ef197b5f6531do/Tube-num-rique-LED-rouge-de-0-36-pouces-4-Bits-4-Bits-Module-d-affichage.jpg_Q90.jpg)

**Comment by sfranzyshen** [comment]
> I have a module of 4 digits but with two 74HC595 chip at the back PCB, which setting should I adjust my sketch please? 2 or 4?

Hi @BullzLabz 

This is not the only driver (Arduino Library) for the 74HC595 chip ... You might consider using a driver (Arduino Library) That is specifically designed to drive these 7-segment displays that use the multiplex mode on the module you are using ... consider looking at one of these drivers instead that support this functionality directly ...
https://miguelpynto.github.io/ShiftDisplay/ 
https://github.com/LuBossCzech/Led4digit74HC595

**Comment by BullzLabz** [comment]
Hello @sfranzyshen ,

Thanks a lot 👍🏻
