### ISSUE TITLE
Unpredictable behavior

### ISSUE THREAD

**Issue by colesnicov** [Simsso/ShiftRegister74HC595#8]
Hello. Is it possible to define a value field like const PROGMEM with your library? Respectively it is possible to use but the device then does not predict my behavior - it does not work .. Me it does not work ..

`const PROGMEM uint8_t pinValues[] = {B10101010}; // not worked!!`

**Comment by Simsso** [comment]
I do not think this is an _issue_ with the library, nor is there any unpredicted behavior. 
[StackOverflow C++](https://stackoverflow.com/questions/tagged/c%2B%2B)

**Comment by colesnicov** [comment]
Did you try to test it? 
`static const uint8_t PROGMEM pinValues [] = {...};`
I think you should know. In any case, I encountered it yesterday while working with your library. I did not play any more, I removed `const static PROGMEM` and everything works as well. Otherwise, the behavior was the following: either the flames of the light were extinguished, not one or the LEDs flashed randomly ...

**Comment by Simsso** [comment]
I did not test it and but I don't even understand what the issue is.

Maybe related to [this](https://www.arduino.cc/reference/en/language/variables/utilities/progmem/)
```
const dataType variableName[] PROGMEM = {}; // use this form
const PROGMEM dataType variableName[] = {}; // or this one
const dataType PROGMEM variableName[] = {}; // not this one
```
